### PR TITLE
Port some straggler testing infrastructure from nose to pytest

### LINKED ISSUE #343: Tests fail to run on Python 3.10 due to nose incompatibility
**Describe the bug**

The file ``test/runTests.py`` has a codepath that executes a shell command. The shell command requires the Python testing framework called ``nose``. Unfortunately, nose is no longer maintained, and it broke starting with Python 3.9 ([see here](https://github.com/nose-devs/nose/issues/1099)). So if you try to run ``python runTests.py`` in the ``test`` folder you'll get an error before any tests run.

**To Reproduce**
1. change directory so you're in the ``test`` folder.
2. run ``python runTests.py ``
3. Get output below.

```
Running tests:
tools
iotest
objects
construction
drivers
report
reportb
algorithms
algorithmsb
optimize
extras
mpi
python3.10 -m nose -v tools iotest objects construction drivers report reportb algorithms algorithmsb optimize extras mpi --with-id
Traceback (most recent call last):
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/__main__.py", line 8, in <module>
    run_exit()
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/loader.py", line 354, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/loader.py", line 183, in loadTestsFromDir
    yield self.loadTestsFromName(
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
    return self.suiteClass(ContextList(tests, context=module))
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/suite.py", line 428, in __call__
    return self.makeSuite(tests, context, **kw)
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/suite.py", line 475, in makeSuite
    suite = self.suiteClass(
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/suite.py", line 159, in __init__
    super(ContextSuite, self).__init__(tests)
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/Users/riley/miniforge3/envs/gsti310/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'

```

**Expected behavior**
Tests are launched (and ideally pass).

**Environment (please complete the following information):**
 - pyGSTi version 0.9.11.2
 - python version 3.10
 - macOS 13.3

### PR DESCRIPTION
**Pull request by rileyjmurray**
I started work on this PR when I got an error upon running ``test/runTests.py``. It turns out that that file tried to use nose, which is long since deprecated and incompatible with Python 3.9 and higher. There was an effort earlier this year to move pyGSTi's testing infrastructure from nose to pytest, but it looks like some things slipped through the cracks. This PR attempts to fill those cracks.

Important notes:
1.  I've taken some liberties by deleting some seemingly unused files. When reviewing this PR, please check that I didn't delete anything important. 
2. I've marked some testing infrastructure as untested (ironically...) or broken, leaving TODOs as applicable. My thought is we can take care of those in another PR.

Edit: this PR is set to resolve #343.

### CODE REVIEW

**Comment by rileyjmurray** [comment]
I realize I didn't explain why I deleted the ``test/test_packages/mpi.old`` folder. I did this because I looked at [the commit history](https://github.com/pyGSTio/pyGSTi/commits/15941e084663f6f0bb87c1d004593dc6b0da4fe3/test/test_packages/mpi.old) for this folder, and it looked like it was deprecated code. In chronological order, the commits affecting this folder were as follows:
* 203f739b563aa7d73dcc928803472b2c730783d2 : this folder is created and existing files in ``test/test_packages/mpi`` are moved here. A new file is created in ``test/test_packages/mpi``.
* cf0b1c07b0971cf9d1de87ee8834f64095cf1974. : clean up import statements
* 408fec04c2a81cc1e2bf9d13ccaba619a58970e2 : clean up whitespace formatting
* 5b6f80b7edb90ac82246f8bd8ec9718e52685088 : find-and-replace some namespace patterns (to reflect a significant pyGSTi refactor)
* d5c7af9e297fbb3b3f4d90c3fb82f46a6886350d : move ``old_testMPIMain.py`` into ``test/test_packages/mpi.old``.

**Comment by coreyostrove** [comment]
Great work, @rileyjmurray!

Deleting the deprecated/unused mpi tests sounds like a great idea to me. I've been thinking that we should consider targeting 0.9.13 (release after the next one coming up) for a spring cleaning of the codebase more broadly, getting rid of unused/deprecated legacy code that we don't want cluttering up the repo any more (and more importantly so we have less to maintain), so this is a great step in that direction.

On the topic of deprecated tests, it may be worth discussing if we also want to remove the notebooks test module from test_packages altogether. As part of the pytest migration earlier this year we switched to using the nbval extension for pytest to do automated testing on our jupyter notebooks, which somewhat obviates the need for this test suite since everything in there should already be covered by the nbval testing.

Thoughts?

**Comment by rileyjmurray** [comment]
Thanks, Corey!

I'm excited to be part of the spring cleaning! Figuring out what _doesn't_ matter in a codebase is a great way to learn about what _does_ matter.

I think there's value in having automated tests for jupyter notebooks. We don't have any such tests over at CVXPY, and we periodically have people report broken example notebooks. I'm under the impression that example notebooks are more important to pyGSTi than they are for CVXPY. For this reason, I'm hesitant to remove ``test_packages/notebooks`` because its existence suggests that _someone_ figured out a way to test notebooks. If I understood how they were being tested in this old code, then that could help in making a pytest-compatible version.

**Comment by sserita** [comment]
Thanks for this PR, Riley! A few notes:

- Removing `mpi.old` seems great. This is probably my fault and should probably have never been pushed up in the first place, so thanks for fixing this.
- I am for removing `test/test_packages/notebooks`. As Corey mentioned, this doesn't mean that we won't be testing the jupyter notebooks. It's just that now the notebook testing is being done via nbval in the GitHub actions instead. Riley, if you still want to maintain this functionality down here to make it easy for users to run, maybe just migrate the relevant lines from .github/workflows/notebook.yml into the runTests script (or an analogous runNotebooks script)?
- Lastly, PRs should merge off of and back into `develop` instead of `master` - we keep `master` clean until it is release time, at which point we ff it up to the tip of develop. Can you merge develop into this branch and then update the PR to push back into develop?

**Comment by coreyostrove** [comment]
One thing worth bookmarking for future us about the current implementation of the notebook testing is that we currently aren't doing any tests of correctness on the cell outputs. The nbval extension for pytest we're using does support this, but at the moment we're only testing whether every cell runs to completion without raising any exceptions. 

Adding this will be a lot of work (there is a bunch of legwork needed to make sure we're only pattern matching on meaningful information and not on random metadata changes in the json), so probably not high-priority at the moment, but at some point we may want to do this.

**Comment by rileyjmurray** [comment]
Okay, great that we're all on board with removing ``mpi.old``.

The fact that you even have tests to make sure all notebook cells execute is great. I don't think the tests in ``test_packages/notebooks`` are doing anything better than that. So I'll remove them. As Corey said, we might want fancier notebook tests in the future, but that's a problem for another day.

**Comment by rileyjmurray** [comment]
Okay, I've made the changes you've requested, @coreyostrove and @sserita. Please review and/or run CI tests, and let me know if anything else is needed!

**Review by sserita — APPROVED** [review]
Everything looks good to me.

**Pull request merged**
