### PR TITLE
Fixing DirectRB notebook

### PR DESCRIPTION
**Pull request by ampolloreno**
There were a couple functions that seemed to have changed.

### CODE REVIEW

**Comment by ampolloreno** [comment]
@enielse @tjproct

**Comment by enielse** [comment]
Some of the changes in the PR use outdated functions, and the current DirectRB.ipynb seems to run fine.  I think we had forgotten to update this notebook at some earlier point, which may have prompted this (sorry!), but I think the current version doesn't need any revision.  Let me know if you think these updates are needed as of pyGSTi version 0.9.7.2.

**Comment by ampolloreno** [comment]
@enielse let me check - I thought I was on master.

**Comment by enielse** [comment]
@ampolloreno - just a ping.  Would it be ok to close this?

**Comment by ampolloreno** [comment]
@enielse Oh sure, sorry about that, got buried under other things. I believe you!

**Pull request closed without merging**
