### PR TITLE
Add Eriks updates: experimental state-space-setting framework; lots of little fixes

### PR DESCRIPTION
**Pull request by enielse**
**A number of accumulated minor fixes along with one experimental feature** to allow setting a model member's state space labels.  This updates `modelmember.py`, `composedop.py`, and `embeddedop.py` and is an experimental feature that hasn't been fully tested yet.  In particular, caches of representation objects will need to be cleared in the forward simulator and/or model to get the approach to work robustly.

Aside from this, the main fixes are:
- computes initial score of forced germs before beginning germ selection iterations so the routine will just exit if the forced germs are amplificationally complete.
- fixes a Label renaming bug, mostly likely to be encountered when renaming a gate in a Circuit.
- fixes to MongoDB serialization related to serializing strings and circuits.
- adds `verbosity` argument to `ConfidenceRegionFactory.project_hessian`
- adds ability to specify `gaugeopt_suite=None` to indicate no gauge optimization should be performed when constructing GST and model test protocol objects.
- when constructing computing reference values for 1D wildcard error, adds fallback to use the trace distance in place of the diamond distance if the latter computation fails.
- fixes a few minor things in the reports: guards Gram matrix failure, argument ordering fix related to constructing a report with wildcard error.
- adds additional include directories in `setup.py` when building cython extensions.  I think these are needed to build on some platforms, maybe M1 macs (?).

### CODE REVIEW

**Comment by sserita** [comment]
Thanks for the quick PR @enielse!

**Review by sserita — APPROVED** [review]
All looks good, thanks for all these fixes! There was no merge conflict with Corey's trivial gauge changes, so I will approve this and we can dedup the functionality as part of spring cleaning.

**Comment by basnijholt** [comment]
Would it be possible to leave to branch up for a little while? We've internally pinned some stuff to this branch and not all of that broke 😭

**Comment by sserita** [comment]
Hi Bas,

No worries, this branch will be staying up for now. I’ll urge to migrate over to pygsti 0.9.12 when it makes sense as it includes these bugfixes and many more, but I realize that is a process for many of our users.

I’ll also mention that at some point this branch will likely just be active in a fork of pyGSTi, but exactly what that looks like is TBD in the near future as we reorganize how we manage the repository.

--
Stefan K. Seritan

From: Bas Nijholt ***@***.***>
Date: Wednesday, December 13, 2023 at 10:30 AM
To: sandialabs/pyGSTi ***@***.***>
Cc: Seritan, Stefan Kelley ***@***.***>, State change ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyGSTi] Add Eriks updates: experimental state-space-setting framework; lots of little fixes (PR #375)

Would it be possible to leave to branch up for a little while? We've internally pinned some stuff to this branch and not all of that broke 😭

**Pull request merged**
